//! Shared help popup content — used by both TUI and GUI renderers.

/// A single help entry: either a section header, a key-description pair, or a blank line.
#[derive(Debug, Clone)]
pub enum HelpEntry {
    /// Section heading (e.g. "Navigation").
    Section(&'static str),
    /// Key binding and its description.
    Shortcut { key: &'static str, desc: &'static str },
    /// Blank separator line.
    Blank,
    /// Dim footer text.
    Footer(&'static str),
}

/// All help entries, shared between TUI and GUI renderers.
pub fn help_entries() -> Vec<HelpEntry> {
    use HelpEntry::*;
    vec![
        Section("Keyboard Shortcuts"),
        Blank,
        Section("Navigation"),
        Shortcut { key: "h/j/k/l",         desc: "Move cursor" },
        Shortcut { key: "w / b / e",        desc: "Word forward / back / end" },
        Shortcut { key: "0 / $",            desc: "Line start / end" },
        Shortcut { key: "gg / G",           desc: "File start / end" },
        Shortcut { key: "f/F + char",       desc: "Find char forward / back" },
        Shortcut { key: "t/T + char",       desc: "Till char forward / back" },
        Shortcut { key: "; / ,",            desc: "Repeat / reverse find" },
        Shortcut { key: "{ / }",            desc: "Paragraph back / forward" },
        Shortcut { key: "( / )",            desc: "Sentence back / forward" },
        Shortcut { key: "%",                desc: "Matching bracket" },
        Shortcut { key: "* / #",            desc: "Search word fwd / back" },
        Shortcut { key: "H / M / L",        desc: "Screen top / mid / bottom" },
        Shortcut { key: "Ctrl+U / Ctrl+D",  desc: "Scroll half page" },
        Shortcut { key: "Ctrl+E / Ctrl+Y",  desc: "Scroll one line down / up" },
        Shortcut { key: "Ctrl+B / PgUp/Dn", desc: "Scroll full page" },
        Shortcut { key: "zz / zt / zb",     desc: "Center / top / bottom" },
        Shortcut { key: "'' / ``",           desc: "Jump to last position" },
        Shortcut { key: "5j / 3k",          desc: "Move N lines" },
        Shortcut { key: "/pattern",          desc: "Search (regex)" },
        Shortcut { key: "n / N",            desc: "Next / prev match" },
        Shortcut { key: "Esc",              desc: "Normal mode" },
        Blank,
        Section("Editing"),
        Shortcut { key: "i / a",            desc: "Insert / Append" },
        Shortcut { key: "I / A",            desc: "Insert line start / end" },
        Shortcut { key: "o / O",            desc: "Open line below / above" },
        Shortcut { key: "Y",                desc: "Yank to end of line" },
        Shortcut { key: "v / Ctrl+V",       desc: "Visual / Block select" },
        Shortcut { key: "gv",               desc: "Reselect last visual" },
        Shortcut { key: "> / < (visual)",    desc: "Indent / Dedent selection" },
        Shortcut { key: "~ / U / u (visual)",desc: "Toggle / Upper / Lower case" },
        Shortcut { key: "R",                desc: "Replace mode (overtype)" },
        Shortcut { key: "r + char",         desc: "Replace single char" },
        Shortcut { key: "x",                desc: "Delete char forward" },
        Shortcut { key: "~",                desc: "Toggle case" },
        Shortcut { key: "u / Ctrl+R",       desc: "Undo / Redo" },
        Shortcut { key: "p / P",            desc: "Paste after / before" },
        Shortcut { key: "dd / 3dd",         desc: "Delete line(s)" },
        Shortcut { key: "cc / C",           desc: "Change line / to end" },
        Shortcut { key: "D / S",            desc: "Delete to end / Subst line" },
        Shortcut { key: "J",                desc: "Join lines" },
        Shortcut { key: ">> / <<",          desc: "Indent / Dedent" },
        Shortcut { key: "==",               desc: "Auto-indent line" },
        Shortcut { key: "Ctrl+A / Ctrl+X",  desc: "Increment / Decrement number" },
        Shortcut { key: "gUw / guw",        desc: "Uppercase / Lowercase motion" },
        Shortcut { key: "gUU / guu",        desc: "Uppercase / Lowercase line" },
        Shortcut { key: "gqq / gq+motion",  desc: "Format/wrap text" },
        Shortcut { key: "\"a + y/d/p",      desc: "Use register a" },
        Shortcut { key: ".",                desc: "Repeat last edit" },
        Shortcut { key: ":",                desc: "Command mode" },
        Shortcut { key: "Tab (in :)",        desc: "Complete cmd/path/option" },
        Blank,
        Section("File"),
        Shortcut { key: "Ctrl+S / :w",      desc: "Save" },
        Shortcut { key: ":q / :q! / :wq",   desc: "Quit / Force / Save+quit" },
        Shortcut { key: ":e <file>",         desc: "Open file" },
        Shortcut { key: "Ctrl+F",            desc: "File finder" },
        Shortcut { key: ":explore",          desc: "File explorer" },
        Shortcut { key: ":ls",               desc: "Buffer list" },
        Shortcut { key: ":bn / :bp",         desc: "Next / prev buffer" },
        Blank,
        Section("Panes (Ctrl+W prefix)"),
        Shortcut { key: "Ctrl+W v / s",     desc: "Split vertical / horiz" },
        Shortcut { key: "Ctrl+W h/j/k/l",   desc: "Move focus" },
        Shortcut { key: "Ctrl+W q",          desc: "Close pane" },
        Shortcut { key: "Ctrl+W t",          desc: "Open terminal" },
        Shortcut { key: "Ctrl+W x",          desc: "Swap panes" },
        Shortcut { key: "Ctrl+W z",          desc: "Toggle zoom pane" },
        Shortcut { key: "Ctrl+W +/-/>/<",    desc: "Resize pane" },
        Shortcut { key: "Ctrl+W [",          desc: "Terminal copy mode" },
        Shortcut { key: "Ctrl+W f",          desc: "File finder" },
        Shortcut { key: "Ctrl+W e",          desc: "Focus explorer" },
        Blank,
        Section("Workspaces"),
        Shortcut { key: ":tabnew <path>",    desc: "New workspace" },
        Shortcut { key: "gt / gT",           desc: "Next / prev workspace" },
        Shortcut { key: "Ctrl+W n / N",      desc: "Next / prev workspace" },
        Shortcut { key: "Ctrl+W L",          desc: "List workspaces" },
        Shortcut { key: "Ctrl+W 1-9",        desc: "Jump to workspace" },
        Shortcut { key: ":tabclose",         desc: "Close workspace" },
        Shortcut { key: ":tabrename <n>",    desc: "Rename workspace" },
        Blank,
        Section("Folding"),
        Shortcut { key: "za",               desc: "Toggle fold at cursor" },
        Shortcut { key: "zM",               desc: "Fold all" },
        Shortcut { key: "zR",               desc: "Unfold all" },
        Blank,
        Section("Multi-Cursor"),
        Shortcut { key: "Alt+Up",           desc: "Add cursor above" },
        Shortcut { key: "Alt+Down",          desc: "Add cursor below" },
        Shortcut { key: "Esc",              desc: "Clear extra cursors" },
        Blank,
        Section("LSP"),
        Shortcut { key: "gd",               desc: "Go to definition" },
        Shortcut { key: "Ctrl+T / :symbols", desc: "Symbol list (fuzzy)" },
        Shortcut { key: ":outline",          desc: "Toggle symbol outline" },
        Shortcut { key: "K (shift)",         desc: "Hover info" },
        Shortcut { key: "Ctrl+N",            desc: "Autocomplete" },
        Blank,
        Section("Macros"),
        Shortcut { key: "Qa",               desc: "Start recording @a" },
        Shortcut { key: "Qa (again)",        desc: "Stop recording" },
        Shortcut { key: "@a",               desc: "Replay macro @a" },
        Shortcut { key: "@@",               desc: "Replay last macro" },
        Blank,
        Section("Marks & Jumps"),
        Shortcut { key: "ma / 'a / `a",      desc: "Set / jump to mark" },
        Shortcut { key: ":marks",            desc: "List all marks" },
        Shortcut { key: "Ctrl+O / Ctrl+I",   desc: "Jump back / forward" },
        Shortcut { key: "gx",               desc: "Open URL under cursor" },
        Shortcut { key: "gf",               desc: "Open file under cursor" },
        Blank,
        Section("Git"),
        Shortcut { key: ":blame / :Gblame",  desc: "Toggle inline git blame" },
        Shortcut { key: ":diff / :Gdiff",    desc: "Side-by-side diff vs HEAD" },
        Blank,
        Section("Quickfix"),
        Shortcut { key: ":make [cmd]",       desc: "Build & populate quickfix" },
        Shortcut { key: ":copen",            desc: "Open quickfix list" },
        Shortcut { key: ":cn / :cp",         desc: "Next / prev quickfix entry" },
        Shortcut { key: ":cclose",           desc: "Close quickfix list" },
        Blank,
        Section("Plugins"),
        Shortcut { key: ":PlugInstall <url>", desc: "Install plugin from git" },
        Shortcut { key: ":PlugUpdate [name]", desc: "Update plugins" },
        Shortcut { key: ":PlugRemove <name>", desc: "Remove plugin" },
        Shortcut { key: ":plugins",          desc: "List loaded plugins" },
        Blank,
        Section("Commands"),
        Shortcut { key: ":!cmd",             desc: "Run shell command" },
        Shortcut { key: ":read file",        desc: "Insert file below cursor" },
        Shortcut { key: ":read !cmd",        desc: "Insert command output" },
        Shortcut { key: ":sort",             desc: "Sort all lines" },
        Shortcut { key: ":w !cmd",           desc: "Pipe buffer to command" },
        Shortcut { key: ":%s/old/new",       desc: "Replace all (regex)" },
        Shortcut { key: ":registers",        desc: "List all registers" },
        Shortcut { key: "q:",                desc: "Command history window" },
        Shortcut { key: "Ctrl+G",            desc: "File info" },
        Shortcut { key: ":cd <dir>",         desc: "Change directory" },
        Shortcut { key: ":mksession",        desc: "Save session" },
        Blank,
        Section("Settings"),
        Shortcut { key: ":set rnu/nonu",     desc: "Line number mode" },
        Shortcut { key: ":set wrap/nowrap",  desc: "Toggle word wrap" },
        Shortcut { key: ":set et/noet",      desc: "Expand tab on/off" },
        Shortcut { key: ":set ts=N",         desc: "Set tab width" },
        Shortcut { key: ":minimap",          desc: "Toggle code minimap" },
        Shortcut { key: "Ctrl+L",            desc: "Redraw screen" },
        Blank,
        Section("Copy Mode (Ctrl+W [)"),
        Shortcut { key: "h/j/k/l",          desc: "Move cursor in scrollback" },
        Shortcut { key: "v",                desc: "Start/toggle selection" },
        Shortcut { key: "y",                desc: "Yank selected text" },
        Shortcut { key: "q / Esc",           desc: "Exit copy mode" },
        Blank,
        Footer("Up/Down scroll | Esc close"),
    ]
}

/// Format a help entry as a plain string (for GUI rendering).
/// Returns `(text, kind)` where kind is "section", "shortcut", "blank", or "footer".
pub fn help_entry_to_plain(entry: &HelpEntry) -> (&'static str, String) {
    match entry {
        HelpEntry::Section(title) => ("section", format!("── {} ──", title)),
        HelpEntry::Shortcut { key, desc } => {
            ("shortcut", format!("  {:<18}{}", key, desc))
        }
        HelpEntry::Blank => ("blank", String::new()),
        HelpEntry::Footer(text) => ("footer", format!("  {}", text)),
    }
}
